stages:
  - build
  - dockerhub

docker:latest:
  stage: build
  only:
    - master
  before_script:
    - export DOCKER_ARGS=${DOCKER_ARGS:-}
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build --pull ${DOCKER_ARGS}
      --build-arg VCS_REF=`git rev-parse --short HEAD`
      --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
      --tag=${CI_REGISTRY}/${CI_PROJECT_PATH} .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}

dockerhub:latest:
  stage: dockerhub
  except:
    - tags
  before_script:
    - apk add --update --no-cache curl
  script:
    - curl -s -H 'Content-Type:application/json' --data '{"build":true}' -X POST https://registry.hub.docker.com/u/datacore/ubuntu-gitlab/trigger/${DOCKERHUB_TOKEN}/ > /dev/null
  when: manual

dockerhub:schedule:
  stage: dockerhub
  only:
    - schedules
  before_script:
    - apk add --update --no-cache curl
  script:
    - curl -s -H 'Content-Type:application/json' --data '{"build":true}' -X POST https://registry.hub.docker.com/u/datacore/ubuntu-gitlab/trigger/${DOCKERHUB_TOKEN}/ > /dev/null
